baseurl = "https://syracuse.io/"
languageCode = "en-us"
title = "Syracuse.io"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Your local developer community"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/header_image.jpg"

#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"

[Author]
#   name = "Some Person"
#   website = "yourwebsite.com"
#   email = "youremail@domain.com"
#   facebook = "username"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "syracuseio"
#   gitlab = "username"
  twitter = "syracuseio"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"

[[menu.main]]
    name = "Groups"
    url = "/groups"
    weight = 1

[[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 2

[[menu.main]]
    name = "Chat"
    url = "/slack/"
    weight = 3


# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1

# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2

